# Generated by Django 4.1.6 on 2023-02-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ektaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentsearch',
            options={'ordering': ('-id',)},
        ),
    ]
