{
    'versionString': 'local',
    'versionCode': 4,
    'name': 'Lucky Casino - Jackpot Slots',
    'shortDescription': 'Maravilloso juego, múltiples formas de jugar, velocidad fluida',
    'description': 'La interfaz es linda, hermosa y no se congela.\nNOTA:El éxito en los juegos de tragaperras del casino social no recompensa con premios de dinero real, ni garantiza el éxito en las apuestas con dinero\n\nRecent changes:\nv1.30',
    'marketCategory': 'CASINO',
    'price': 'free',
    'apkSize': 43613539,
    'maturityLevel': 'HIGH',
    'supportsApp2SD': 'FALSE',
    'launchTime': 1672444800,
    'lastAppUpdateTime': 1672444800,
    'infoRefreshTime': 1675048134,
    'downloadsCategory': '10,000+',
    'estimatedDownloads': 26000,
    'estimatedRecentDownloads': 26000,
    'rating': 0.0,
    'recentRating': 0.0,
    'ratingCount': 0,
    'rating1StarCount': 0,
    'rating2StarCount': 0,
    'rating3StarCount': 0,
    'rating4StarCount': 0,
    'rating5StarCount': 0,
    'plusOneCount': 0,
    'commentCount': 0,
    'iconUrl': 'https://lh3.googleusercontent.com/JUaXawMRj0rYNhPikyqrvcmhWoSPof-xhuV5QXXOSl7UOe2eYW2XzTyImtBQeVJqeBDX-HuTYVOWl9nU-iyHLAYy-X1PZP1zNoJ8WA',
    'featureGraphicUrl': 'https://lh3.googleusercontent.com/wZJE9V1xPQ1_Mp-zKwgUZQR3TI47f4Mf2s1S1kps65NDhE-pQ9zMt2raUj4-uQxa_76ZC7bg4kMSb78V8FJu8GnQNF3xY3SQYCotUw',
    'developerName': 'AlimSher1999',
    'developerEmail': 'alimalimsher55@gmail.com',
    'developerAddress': '',
    'website': 'https://gfdfe12.com/',
    'package': 'andmosico.andcasino.andlucky',
    'screenshotUrls': ['https://lh3.googleusercontent.com/Xl9CU9nW8slaCsmq8BhoWzgQMTHOBwAAMAnReXnsjJK8oZOW0Le4tPqO4r__oPTGwHgjtmkJWOxnMUxYsSiKpA77GcOD1SziR-hPJA', 'https://lh3.googleusercontent.com/8MfVbCFtTXk-XwC2Z9WA9cXpWM59G7vW3MXuqNAdf3v88ryrumBEIocfcZcSclTjnkbsN0XMHxOKLJXwF3PJyzsoyPy86-8drbqz', 'https://lh3.googleusercontent.com/cB07jlhAQSTCrz5Pa8b0PX4m2pyJ2mewoJUCbMs8zEpGGPU61c_fq1J6xzlFIFWcyYdmj0zvp6IW1ZOcRvbsKlP04mRH0E7JlRQ', 'https://lh3.googleusercontent.com/QtFIL1Qci-y-l5qrhtfPe29WiMsH4dYJHaUiyKwBwmy5ZcQ2khhXf42LWjxf76sYz29hQkNuy3Q-31HxUmrkqwGkOrRSdMtIehb-'],
    'permissions': ['android.permission.ACCESS_COARSE_LOCATION', 'android.permission.ACCESS_FINE_LOCATION', 'android.permission.ACCESS_NETWORK_STATE', 'android.permission.ACCESS_WIFI_STATE', 'android.permission.BROADCAST_STICKY', 'android.permission.CAMERA', 'android.permission.CHANGE_CONFIGURATION', 'android.permission.CHANGE_NETWORK_STATE', 'android.permission.CHANGE_WIFI_STATE', 'android.permission.INTERNET', 'android.permission.KILL_BACKGROUND_PROCESSES', 'android.permission.MODIFY_AUDIO_SETTINGS', 'android.permission.MOUNT_UNMOUNT_FILESYSTEMS', 'android.permission.READ_EXTERNAL_STORAGE', 'android.permission.READ_LOGS', 'android.permission.READ_PHONE_STATE', 'android.permission.RECEIVE_BOOT_COMPLETED', 'android.permission.RECEIVE_USER_PRESENT', 'android.permission.RECORD_AUDIO', 'android.permission.SYSTEM_ALERT_WINDOW', 'android.permission.VIBRATE', 'android.permission.WAKE_LOCK', 'android.permission.WRITE_EXTERNAL_STORAGE', 'android.permission.WRITE_SETTINGS', 'oicq.wlogin_sdk.permission.WloginProvider.READ', 'oicq.wlogin_sdk.permission.WloginProvider.WRITE']
}