# Generated by Django 4.1.5 on 2023-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='encodings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
