"""empty message

Revision ID: fa3abb1b07c7
Revises: 75f59d7177d2
Create Date: 2023-02-01 16:03:01.334482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3abb1b07c7'
down_revision = '75f59d7177d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
